In [18]:
#calculating focal loss


import torch
import torch.nn.functional as F
import numpy as np

from losses.focal_loss import FocalLoss, reweight

def logit(p: torch.Tensor) -> torch.Tensor:
    return torch.log(p / (1 - p))


In [5]:
print('inputs shape', inputs.shape)
inputs = logit(
    torch.tensor(
        [
            [
                [0.95, 0.55, 0.12, 0.05],
                [0.09, 0.95, 0.36, 0.11],
                [0.06, 0.12, 0.56, 0.07],
                [0.09, 0.15, 0.25, 0.45],
            ]
        ],
        dtype=torch.float32,
    ).squeeze(0)
)
print('target shape', targets.shape)
targets = torch.tensor([1, 3, 0, 2], dtype=torch.long).squeeze(0)

#
print('inputs shape', inputs.shape)
print('target shape', targets.shape)

inputs shape torch.Size([4, 4])
target shape torch.Size([4])


In [11]:
print(inputs)
print(targets)
print(targets.ndim)

tensor([[ 2.9444,  0.2007, -1.9924, -2.9444],
        [-2.3136,  2.9444, -0.5754, -2.0907],
        [-2.7515, -1.9924,  0.2412, -2.5867],
        [-2.3136, -1.7346, -1.0986, -0.2007]])
tensor([1, 3, 0, 2])
1


In [13]:
#print shape before squeeze
print(logit(
    torch.tensor(
        [
            [
                [0.95, 0.55, 0.12, 0.05],
                [0.09, 0.95, 0.36, 0.11],
                [0.06, 0.12, 0.56, 0.07],
                [0.09, 0.15, 0.25, 0.45],
            ]
        ],
        dtype=torch.float32,
    )).shape)
print(torch.tensor([1, 3, 0, 2]).shape)
print(inputs.shape[0])

torch.Size([1, 4, 4])
torch.Size([4])
4


In [12]:
# get unique elements and their counts in a tensor
x = torch.tensor([1, 1, 2, 2, 3, 1, 1, 2])
unique_elements, counts = torch.unique(x, return_counts=True)

print("Unique elements:", unique_elements)
print("Counts:", counts)


Unique elements: tensor([1, 2, 3])
Counts: tensor([4, 3, 1])


In [33]:
#learn F.logSoftmax
N = targets.shape[0]
log_p = F.log_softmax(inputs, dim=1)        #output is [4,4]
N = targets.shape[0]      #batch size
log_pt = log_p[torch.arange(N), targets]    #torch.Size([4])
print("log_p: ", log_p.shape)
print("log_pt: ", log_pt.shape)


log_p:  torch.Size([4, 4])
log_pt:  torch.Size([4])
tensor([0.0599, 0.0062, 0.0412, 0.2336])


In [34]:
pt = log_pt.exp()
print(pt)

sample_weights = pt

tensor([0.0599, 0.0062, 0.0412, 0.2336])
